### PR TITLE
Level 1 routines.

### PR DESCRIPTION
**Pull request by yangjueji**
Blas level 1 routines and their tests.

### CODE REVIEW

**Comment by cartazio** [comment]
woah, good work!
any idea why theres a test failure for 

```
  sdsdot on vectors of lengths 6 and 12 with incx 2 and 4: FAIL
        expected: 63.0
         but got: 4.5563e-41
``` 
?

**Comment by cartazio** [comment]
I'll do some code review over the next few days

**Comment by yangjueji** [comment]
sdsdot failure exists in my Arch Linux before(https://bugs.archlinux.org/task/45325). But after the cblas bug is fixed, it turns to be correct.
Maybe travis-ci.org also is using the cblas lib with bug. How can I get to know which cblas lib it is using?

**Comment by cartazio** [comment]
its using Ubuntu 12.04 LTS Server Edition 64 bit

**Comment by cartazio** [comment]
@yangjueji  ok, so i guess one question we need to ask is this: do we want to directly bind the fortran api version of the sdsdot function so we can avoid that bug, or accept that its going to fail on travis?

**Comment by cartazio** [comment]
i'll see about reporting this bug to the ubuntu folks

**Comment by yangjueji** [comment]
I found a Ubuntu Kylin 14.04 LTS and passed all the tests.

**Comment by cartazio** [comment]
ok, thats good to know.

i'll do some extra work on top of this PR to make it build with travis CI this week (though in the long run whatever work arounds i do for making travis CI happy should be removed)

I do think for the work on level 2 and level 3 routines we'll have to work a bit more closely back and forth on some of the api details. i'm excited and I hope you are to!

(merging in the level 1 routines doesn't block you from starting to think about that, and dont forget to ping me on IRC / email whenever you hit a design challenge / question)

**Comment by cartazio** [comment]
i'm kicking off a new build to see if the ubuntu LTS 12 version of C blas has been patched yet. if not i'll merge it in as is, and i'll help hack out a work around for that cblas bug

**Comment by cartazio** [comment]
hrm, i need to fix show! do you think we should directly call fortran sdsdot or that we should copy the cblas wrapper and just include that as a c file in hblas?

**Comment by cartazio** [comment]
@yangjueji  any progress on the `sdsdot_`  code?

**Comment by yangjueji** [comment]
Good news: To return float will get a correct result. But to return double will not.
Bad news: To return float will not get a correct result in my Mac... But to return double will do.

**Comment by cartazio** [comment]
Ok.  This is tricky.  I'll get back to you on this today.

**Pull request merged**
