### PR TITLE
Port test suite to hspec

### PR DESCRIPTION
**Pull request by Tclv**
This PR contains code to port tests from tasty to hspec. In this process I tried to keep the directory structure as much as possible in line with the hspec convention.

Did not touch the test messages for the time being. If those require any changes that's probably better served for a different PR.

To show the complete output in stdout instead of only failures run the tests with 
`cabal test --show-details=always --test-option=--color`

Currently one test fails, that is also failing on the master. There are a couple of pending tests that reference to code that does not compile on the current master. The tests are commented out and the  specs are left with `pending` stubs. As the code on the master does not compile a runnable demo can be found at https://github.com/Tclv/hblas/tree/demo-tests that removed some non-compiling code.

### CODE REVIEW

**Comment by cartazio** [comment]
hey! i'm not getting around to prepping a new release, care to rebase on top of current master (i may just see if i can cherry pick this :) )

**Comment by Tclv** [comment]
Sure I'll have a look!

**Comment by Tclv** [comment]
The rebase seems to have worked. The tests run fine local on my machine. I'm at a loss why Travis is not able to run the tests though. The offending line seems to be
`ghc: could not execute: hspec-discover`
This is the Hspec test preprocessor (http://hspec.github.io/hspec-discover.html).

I am unfamiliar with Travis. Would you prefer fixing Travis or manually importing the tests in `Spec.hs`?

**Comment by cartazio** [comment]
NO HSPEC DISCOVER BAD  BAD

**Comment by cartazio** [comment]
I would prefer you WRITE imports and exports

**Comment by cartazio** [comment]
;)

**Comment by cartazio** [comment]
i've previously hacked hspec discover into working, and honestly i'm pro *not* using it :)

**Comment by Tclv** [comment]
Alright manual imports it is. Travis passes now!

**Comment by cartazio** [comment]
I like how the level 2 and 3 files actually give a diff of old and new.  Is it possible to replicate that also for level 1?

**Comment by Tclv** [comment]
I am not sure. It used to be like that for the original fork and the first rebase, but another rebase and git stopped recognising it as a move. I am not aware of an easy fix for that besides rebasing again from the original fork and crossing my fingers really hard?

**Comment by cartazio** [comment]
First do the git move/rename the files , then for each commit over write the file with the target new state?

Not sure how to use rebase to do that ... :)

**Comment by Tclv** [comment]
Hmm I'll have a look at it later this week. Surely there's someone who has solved this before ;)

**Comment by cartazio** [comment]
cool, now lets just get those diffs all purdy with git recognizing the mv edit sequences :)

**Comment by Tclv** [comment]
I rebased and corrected the individual commits. Currently the commits show the git mv in 82fc983 and the actual modification in fbd5570 of `Level1.hs/Level1Spec.hs`. This test gets a final move in 108ac52 to match the conventional structure better. The chain in the individual commits should be okay now, yet in the PR aggregate files changed tab it shows it as a separate file deletion and creation. I am at a loss why it shows it like that. Any ideas?

**Comment by cartazio** [comment]
gh diff is lame, i'll take a look this weekend and merge stuff in :) 

thanks!

**Comment by cartazio** [comment]
ok, finally cherry picked and in the process of validating and pushign to master :)

**Pull request closed without merging**
